name: Create Lambda Function with Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t lambda-docker .
          docker tag lambda-docker:latest fazlulkarim105925/lambda-docket:latest
          docker push fazlulkarim105925/lambda-docket:latest

      - name: Create AWS Lambda function with Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda create-function \
            --function-name my-lambda-function \
            --package-type Image \
            --code ImageUri=fazlulkarim105925/lambda-docket:latest \
            --role arn:aws:iam::<your-account-id>:role/<your-lambda-execution-role> \
            --region us-east-1
